name: Angular CI

on:
  push: 
    branches: [ main ] 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x' 
    - name: angular
      run: npm ci
    - name: Test
      run: npm run build && npm run test 
    - name: Check LCOV
      run: cat ${{ github.workspace }}/coverage/lcov.info
    - name: lcov check but different
      run: cat coverage/lcov.info
    # - name: List files in workspace
    #   run: ls -la ${{ github.workspace }}

  sonarcloud-scan:
    runs-on: ubuntu-latest
    needs: test  # This job will run only after the 'test' job completes successfully
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 
    - name: SonarCloud Scans
      uses: SonarSource/sonarcloud-github-action@master
      with:
        args: -Dsonar.working.directory=${{ github.workspace }} 
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
