name: Angular CI

on:
  push: 
    branches: [ main ] 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x' 
    - name: angular
      run: npm ci
    - name: Test
      run: npm run build && npm run test 
    - name: Check LCOV
      run: cat ${{ github.workspace }}/coverage/sample-app/lcov.info
    - name: lcov check but different
      run: cat coverage/sample-app/lcov.info
    # - name: List files in workspace
    #   run: ls -la ${{ github.workspace }}

  sonarcloud-scan:
    runs-on: ubuntu-latest
    needs: test  # This job will run only after the 'test' job completes successfully
    steps:
    # - uses: actions/checkout@v2
    #   with:
    #     fetch-depth: 0 
    - name: SonarCloud Scans
      uses: SonarSource/sonarcloud-github-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        WORKING_DIR:  ${{ github.workspace }}
      with:
        args:
          -Dsonar.working.directory=${{ github.workspace }} 
          -Dsonar.projectKey=vijaykrishna2520_sample-app-angular
          -Dsonar.javascript.lcov.reportPaths=${{ env.WORKING_DIR }}/coverage/${{ env.SONAR_PROJECT_NAME }}/lcov.info
          -Dsonar.organization=vijaykrishna2520
          -Dsonar.projectBaseDir=. 
          -Dsonar.sourceEncoding=UTF-8
          -Dsonar.projectName=sample-app 
          -Dsonar.projectVersion=1.0 
          -Dsonar.sources=src
          -Dsonar.inclusions=**/*.ts 
          -Dsonar.tests=src 
          -Dsonar.test.inclusions=**/*.spec.ts 
          -Dsonar.typescript.lcov.reportPaths=coverage/${{ env.SONAR_PROJECT_NAME }}/lcov.info
          -Dsonar.log.level=INFO
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.working.directory=${{env.WORKING_DIR}
