name: Angular CI

on:
  push: 
    branches: [ main ]  # Or your default branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Ensure full history is fetched
    - name: Setup Node.js and Install dependencies
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'  # Or your preferred Node.js version

    - name: Run Tests
      run: npm run test 


    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
